import requests
import json

lstr = []
ljson = []
names1 = []
names = []
fnjs = []

with open('output.txt') as d1:
    lstr = d1.readlines()
    #print(lstr)
    for i in lstr:
        #print(i.strip('\n'))
        ljson.append(json.loads(i))

with open('names.txt') as d1:
    names1 = d1.readlines()
    #print(names1)
    for i in names1:
        names.append(i.strip())
        if len(i.strip()) == 0:
            names.remove(i.strip())

#names = ['S&P 500 Consolidated - CHICAGO MERCANTILE EXCHANGE', 'DJIA Consolidated - CHICAGO BOARD OF TRADE', 'NASDAQ-100 Consolidated - CHICAGO MERCANTILE EXCHANGE', 'RUSSELL 2000 MINI INDEX FUTURE - ICE FUTURES U.S.', 'NIKKEI STOCK AVERAGE - CHICAGO MERCANTILE EXCHANGE', 'U.S. TREASURY BONDS - CHICAGO BOARD OF TRADE', '2-YEAR U.S. TREASURY NOTES - CHICAGO BOARD OF TRADE', '5-YEAR U.S. TREASURY NOTES - CHICAGO BOARD OF TRADE', '10-YEAR U.S. TREASURY NOTES - CHICAGO BOARD OF TRADE', '30-DAY FEDERAL FUNDS - CHICAGO BOARD OF TRADE', 'BITCOIN-USD - CBOE FUTURES EXCHANGE', 'EURO FX - CHICAGO MERCANTILE EXCHANGE', 'AUSTRALIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE', 'EURO FX - CHICAGO MERCANTILE EXCHANGE', 'BRITISH POUND STERLING - CHICAGO MERCANTILE EXCHANGE', 'JAPANESE YEN - CHICAGO MERCANTILE EXCHANGE', 'CANADIAN DOLLAR - CHICAGO MERCANTILE EXCHANGE', 'MEXICAN PESO - CHICAGO MERCANTILE EXCHANGE', 'NEW ZEALAND DOLLAR - CHICAGO MERCANTILE EXCHANGE', 'RUSSIAN RUBLE - CHICAGO MERCANTILE EXCHANGE', 'SWISS FRANC - CHICAGO MERCANTILE EXCHANGE', 'GOLD - COMMODITY EXCHANGE INC.', 'SILVER - COMMODITY EXCHANGE INC.', 'PLATINUM - NEW YORK MERCANTILE EXCHANGE', 'PALLADIUM - NEW YORK MERCANTILE EXCHANGE', 'COPPER-GRADE #1 - COMMODITY EXCHANGE INC.', 'CRUDE OIL, LIGHT SWEET - NEW YORK MERCANTILE EXCHANGE', 'GASOLINE BLENDSTOCK (RBOB) - NEW YORK MERCANTILE EXCHANGE', 'NO. 2 HEATING OIL, N.Y. HARBOR - NEW YORK MERCANTILE EXCHANGE', 'NATURAL GAS - NEW YORK MERCANTILE EXCHANGE', 'CBT ETHANOL - CHICAGO BOARD OF TRADE', 'CORN - CHICAGO BOARD OF TRADE', 'WHEAT-SRW - CHICAGO BOARD OF TRADE', 'ROUGH RICE - CHICAGO BOARD OF TRADE', 'OATS - CHICAGO BOARD OF TRADE', 'SOYBEANS - CHICAGO BOARD OF TRADE', 'SOYBEAN MEAL - CHICAGO BOARD OF TRADE', 'SOYBEAN OIL - CHICAGO BOARD OF TRADE', 'COCOA - ICE FUTURES U.S.', 'COTTON NO. 2 - ICE FUTURES U.S.', 'FRZN CONCENTRATED ORANGE JUICE - ICE FUTURES U.S.', 'COFFEE C - ICE FUTURES U.S.', 'SUGAR NO. 11 - ICE FUTURES U.S.', 'RANDOM LENGTH LUMBER - CHICAGO MERCANTILE EXCHANGE', 'LIVE CATTLE - CHICAGO MERCANTILE EXCHANGE', 'FEEDER CATTLE - CHICAGO MERCANTILE EXCHANGE']

for i in ljson:
    if i['name'] in names:
        fnjs.append(json.dumps(i))

lnames = []
for i in names:
    for a in ljson:
        if i in a['name']:
            lnames.append(i)
        else:
            continue

for i in names:
    if i in lnames:
        pass
    else:
        print(i)
